import { approveScenario, submitScenario } from "@/app/actions";
import { ScenarioForm } from "@/components/scenario-form";
import { SubmitButton } from "@/components/submit-button";
import { getScenarioData } from "@/lib/data";
import { requireUser } from "@/lib/session";

export default async function ScenariosPage() {
  const user = await requireUser(); const data = await getScenarioData();
  return <main className="page-shell"><div className="page-heading"><div><p className="eyebrow">Versioned calculation</p><h1>Capacity Planning</h1><p className="page-subtitle">Demand, available time, takt, UPH, loading, utilization, capacity, and manpower with visible assumptions.</p></div></div><ScenarioForm balances={data.balances as never[]} shifts={data.shifts as never[]}/><section className="scenario-list">{data.scenarios.map((scenario) => <article className="panel scenario-card" key={scenario.id}><div className="scenario-head"><div><p className="eyebrow">{scenario.scenario_number} · {scenario.model_code} · {scenario.line_code}</p><h2>{scenario.name}</h2></div><span className={`status-pill status-pill--${scenario.status}`}>{scenario.status}</span></div><div className="scenario-assumptions"><span>Shift {minutes(scenario.shift_seconds)}</span><span>Break {minutes(scenario.break_seconds)}</span><span>Meeting {minutes(scenario.meeting_seconds)}</span><span>Setup {minutes(scenario.setup_seconds)}</span><span>Planned downtime {minutes(scenario.planned_downtime_seconds)}</span><strong>Available {minutes(scenario.available_time_seconds)}</strong></div><div className="scenario-metrics"><div><span>Demand</span><strong>{scenario.target_quantity}<small> unit</small></strong></div><div><span>Takt</span><strong>{scenario.takt_time_seconds}<small> sec/unit</small></strong></div><div><span>UPH</span><strong>{scenario.units_per_hour}<small> unit/hr</small></strong></div><div><span>Capacity</span><strong>{scenario.theoretical_capacity}<small> unit/shift</small></strong></div><div><span>Loading</span><strong>{scenario.loading_pct}<small>%</small></strong></div><div><span>Time utilization</span><strong>{scenario.time_utilization_pct}<small>%</small></strong></div><div><span>Bottleneck</span><strong>{scenario.bottleneck_cycle_seconds}<small> sec</small></strong><small>{scenario.bottleneck_station}</small></div><div><span>Manpower</span><strong>{scenario.theoretical_manpower}<small> operator</small></strong></div><div><span>Line efficiency</span><strong>{scenario.line_efficiency_pct}<small>%</small></strong><small>{scenario.balance_loss_pct}% balance loss</small></div></div>{scenario.status === "draft" && <form action={submitScenario}><input type="hidden" name="id" value={scenario.id}/><SubmitButton className="button button--secondary">Submit conclusion</SubmitButton></form>}{scenario.status === "submitted" && user.role === "supervisor" && <form action={approveScenario}><input type="hidden" name="id" value={scenario.id}/><SubmitButton>Approve conclusion</SubmitButton></form>}</article>)}{!data.scenarios.length && <div className="panel panel-empty panel-empty--large">No capacity scenario yet. Create a Line Balance first.</div>}</section></main>;
}

function minutes(seconds: number) {
  return `${Math.round(Number(seconds) / 60)} min`;
}
