import { LineBalanceForm } from "@/components/line-balance-form";
import { getLineBalanceData } from "@/lib/data";

export default async function LineBalancePage() {
  const data = await getLineBalanceData();
  return <main className="page-shell"><div className="page-heading"><div><p className="eyebrow">Work distribution</p><h1>Line Balance</h1><p className="page-subtitle">Assign approved process elements to active stations. Station load is calculated, never typed.</p></div></div><LineBalanceForm models={data.models as never[]} lines={data.lines as never[]} stations={data.stations as never[]} standards={data.standards as never[]}/>
    <section className="balance-list">{data.balances.map((balance) => { const rows = data.assignments.filter((item) => item.line_balance_id === balance.id); const stationCodes = [...new Set(rows.map((item) => item.station_code))]; const loads = stationCodes.map((code) => ({ code, seconds: rows.filter((item) => item.station_code === code).reduce((sum, item) => sum + Number(item.standard_time_seconds), 0), rows: rows.filter((item) => item.station_code === code) })); const max = Math.max(...loads.map((load) => load.seconds), 1); return <article className="panel yamazumi-card" key={balance.id}><div className="panel-heading"><div><p className="eyebrow">{balance.model_code} · {balance.line_code} · Revision {balance.revision}</p><h2>{balance.name}</h2></div><span>{balance.element_count} elements</span></div><div className="yamazumi"><div className="takt-placeholder"><span>Bottleneck {max.toFixed(2)} sec</span></div>{loads.map((load) => <div className="yama-station" key={load.code}><div className="yama-bar" style={{ height: `${Math.max((load.seconds / max) * 180, 12)}px` }}>{load.rows.map((row, index) => <span key={row.process_code} style={{ flex: Number(row.standard_time_seconds) }} title={`${row.process_code}: ${row.standard_time_seconds} sec`} data-tone={index % 3}/>)}</div><strong>{load.seconds.toFixed(2)}</strong><small>{load.code}</small></div>)}</div></article>; })}{!data.balances.length && <div className="panel panel-empty panel-empty--large">Belum ada Line Balance. Approve Standard Time terlebih dahulu.</div>}</section>
  </main>;
}
